# Generated by Django 4.1.6 on 2023-02-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uzduotis',
            options={'ordering': ['-data'], 'verbose_name': 'Užduotis', 'verbose_name_plural': 'Užduotys'},
        ),
        migrations.AlterField(
            model_name='uzduotis',
            name='data',
            field=models.DateTimeField(null=True, verbose_name='Laikas'),
        ),
    ]
