# Generated by Django 4.1.6 on 2023-02-09 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_alter_uzduotis_options_alter_uzduotis_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uzduotis',
            name='body',
            field=models.CharField(max_length=200, verbose_name='Tekstas'),
        ),
        migrations.AlterField(
            model_name='uzduotis',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzduotys', to=settings.AUTH_USER_MODEL),
        ),
    ]
